language: ruby
sudo: false
dist: focal
rvm:
- 2.5.0
- 2.7.1
- 3.0.0
script:
- "./bin/git-maintain --help"
- "gem build git-maintain.gemspec"
deploy:
  - provider: releases
    api_key:
      secure: KUF0GE5u4xZwAAk0SjW1IDRotgOiNitZDPQnvy/4MVuwtXBNb1F42jMyfFN8rsMfz2gcJUy84XPCfW9rNZbJgWiUA0x0kSoUHc4weLgw7XJNgrGkEVzwXEFJnwpEw4xBe7XsGD37g+IcHPOZEFW1gC8jmGD9evJDqaXaxygUqtxLiAmu24efdonqCLyvyct1lJNdIuz2M9sWRSRniVaB9lq3ag6Uy3IG+cZ0U+RZnjX8mrZfnv+mARWjWWWLq5DMg7Wze1BTC4y2ZYWuPLPToQDB5g6pZyomd3du5JKIODOT84bFjZmiW6EvSEzhw6R2/o8A52QqChvAszB8h/4lox6mF7DThD3njkqLgij1ct1Oy0nAXZM4NvYbepGzJ28BgS+61rzScwi35ClE8E4rTMEbG019vWlvqB6RT4HhuhIXLNY06oKB2fIAmRL2hRl0fouivt/0ZparmIubQbsUEXAUjarqZZGeXQEdt1q7OloXS9DHsUUC52apdxeVxVPTfSWcnE6Zf1+/+BBriOjcWrq/YajpV0vgKXGvorYfHDv8K/48I1ri2WQ1NCUtNkeFxOXgWu7yzR8Byu+YrXEMOP6cDv1/ZNt4GazGKKT1k5jjGcSR1bqnfFbO/biRMNJmtxcGI4MscR33dYiQA8VGvyiCPD5NePHP+dosZowEkf0=
    skip_cleanup: true
    file_glob: true
    file: git-maintain*.gem
    on:
      repo: nmorey/git-maintain
      tags: true
  - provider: rubygems
    api_key:
      secure: hr+kAW+j6Cz3sT4YB9mA88EVkNwjWwO2XsL2L0/O9zwMxQI3eY+sCCfTzE78uNzZCBxv+w+AwEdSe0Qee1SR0okOC8A1k38mdvfOgATzjB8Sxn0lrbHxf4YjgHs3dZesGmmmkv8Ydp3YDHeUgNexTuILj1WNMolHS7aP+It+LMiAEJQ+Zq2XOit8/D+0u5k/Ph/MZyalnT2itlsAjlPtWNg6C2Swh9+PlkQe6QgAqKGRnUtTchfja2Dpo9/nu7b1So5A1kyiysZzQ1tyEtVwpAl6HLGg8pG6iYjftTZamB0zSQa/ViCqINI8aCYXqKGZ/w676Ds26bt29FoSHTUdjMp8k/PK4BpWMP8yhw6jE+aaUAw35/urN/gmq019w8GlEvYFEYVr52qPr1rtcbD2EKiZasgFkRQ9RkIWHsgId2DiqJsviOyF+lrK6fsjDhZ/hL9YzhoQOF4hDjIdHsD1RGqjZIgJlmY9KwMhs+1utoi5y7aLe8KtOxhTB9l+fnZ6NpOg5wlz6y8AZG7sS1FSXucaH4qy837wcPg+h7GIbGjW+fOrzqYN5Y/VzPPuFDJNMuCE1P1AhRoapEgRPCTA1DhT+ICvs6K1ZUtMIhREbZMacQzWDPVV35SV+bq3fo1E3GnwHYtx3jTLbFYMG0knYSpo2JoDFjRETLtQeunbDEQ=
    on:
      tags: true
    gemspec: git-maintain.gemspec
